/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhahang.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Anh Tiến ơi.Có Trộm!
 */
public class DanhMucBan extends javax.swing.JPanel {

    /**
     * Creates new form abc
     */
    int length = 5;
    int tongSoBan = 15;
    int banHienTai = 0;
    int sotrang = 1;
    JButton[] listBan = new JButton[tongSoBan];
    JButton[] listtrang = new JButton[sotrang];
    public DanhMucBan() {
        initComponents();
        int sohang = tongSoBan / length;
            
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (e.getSource() instanceof JButton) {
                      QuanLyThanhToan quanlythanhtoan = new QuanLyThanhToan();
                      quanlythanhtoan.setVisible(true);
                }
            }
        };
         // xử lí tự động chỉnh khi thêm bàn hoặc xóa bàn
        int x = 30;
        int y = 20;
        int count = 1;
        for (int i = 0; i < tongSoBan; i++) {
            // chỉnh vị trí bàn
            listBan[i] = new JButton("Bàn " + (i + 1));
            listBan[i].setBounds(x, y, 200, 150);
            listBan[i].setBackground(new Color(142, 242, 144));
            listBan[i].setForeground(Color.black);
            listBan[i].setFont(new Font("Serif", Font.PLAIN, 24));
            banHienTai = i;
            listBan[i].addActionListener(listener);
            
            // xử lí khi thêm 1 bàn mới và add bàn vào danh sách list bàn
            x += 240;
            // chỉnh tọa độ danh sách bàn
            if (i + 1 == count * length) {
                count++;
                y += 170;
                x = 30;
            }

            this.add(listBan[i]);
            
        }
        
        ActionListener listener1 = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (e.getSource()instanceof JButton) {
                     QuanLyThanhToan quanlythanhtoan = new QuanLyThanhToan();
                      quanlythanhtoan.setVisible(true);
                }
            }
        };
                
        int sotrang = tongSoBan/15;
        x = 590;
        y = 490;
        for (int i = 0; i < sotrang; i++) {
            listtrang[i] = new JButton(""+(sotrang+1));
            listtrang[i].setBounds(x, y, 50, 40);
            listtrang[i].addActionListener(listener);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1129, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
